version: "3.8"

services:
    mongo:
        image: mongo:latest
        container_name: buenas-tche-mongo
        ports:
            - "27017:27017"
        volumes:
            - ./mongo_data:/data/db
            - ./mongod.conf:/etc/mongod.conf
        restart: unless-stopped
        command: --config /etc/mongod.conf

    app:
        build: .
        container_name: app
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        depends_on:
            - mongo
        env_file:
            - .env
        restart: always
        command: node server.js
        tty: true

volumes:
    mongo_data:
        driver: local
